strata.js
@danvarga  can you please review, i am getting a 400 bad request while using this end point, i checked the same data i am passing in a curl and it works. I am a little sceptical about the content type and accept headers, but confirmed from strata guys that is fine.
Have we done any post operation with the similar content types.
eg.  var escalationJSON = {'account_number': "540155",'case_number': "00531482",'geo': "LATAM",'subject': "test sales subject",'record_type': "Sales Escalation",'issue_description': "test description"};
eg curl:  
curl -v -k -u skesharigit:redhat -X POST -H 'Content-Type:application/vnd.redhat.escalation+json'   -H 'Accept: application/vnd.redhat.escalation+json' --data '{"account_number": "540155","case_number": "00531482","geo": "LATAM","subject": "test sales …
=> added feature for escalation request

strata.js
@sshumake can you please take a look and let me know. I am a little skeptical about the last parameter [array of params] if that would be passed by clients correctly and not break our query. I did not not do anything fancy with it and just iterated and added to the parent.
=> Added wrapper for SOLR search query

strata.js
@sshumake pls review and merge !
=> Added file attachment max size

strata.js
@sshumake @renujhamtani pls review and merge !
=> Fix for SOLR special char search

bower.json, strata.js
=> passed solutionReviewSelector in ajaxrequest

bower.json, strata.js
@vrathee @renujhamtani Please review
=> PCM 1525 - added function to fetch external tracker updates for a case

bower.json, strata.js
@vrathee @renujhamtani Please review
=> PCM-1526 checking if response is null and then assigning values to avoid console errors

bower.json, strata.js
@gandhikeyur @renujhamtani Please Review
=> Fix PCM-566

bower.json, strata.js
@gandhikeyur @renujhamtani Please review.
=> PCM-1429: Added POST for solutions

bower.json, strata.js
@renu @gandhikeyur Please review.
=> PCM-1694: Added /rs/recommendatios support

bower.json, strata.js
=> PCM-1694: Added highlight for recommendations API

bower.json, strata.js, test/js/strata-driver.js
Primarily shoring up the recommendations for a case and adding a testcase for that.
Also adding score to both recommendations and search so we can sort by that in the UI.
Minor formatting and editing as well.
Version bumped so we need a new push to bower.
=> Fixing recommendationsForCase, adding score to search and recommendations

bower.json, strata.js
=> PCM-1027: Added paging support and ordering to advanced case search

bower.json, strata.js
@vrathee @gandhikeyur @engineersamuel  Please review.
=> PCM-1979: Added bookmark API

bower.json, strata.js
@renujhamtani @gandhikeyur Please Review
=> Fix for PCM-2781

bower.json, strata.js
@gandhikeyur @jtrantin Please review
=> jsuri issue on CI

bower.json, strata.js
=> PCM-3133: Added getUserBySSO

bower.json, strata.js
@vrathee @gandhikeyur Fixed jsUri escaping that broke case search. Please review and publish this.
=> Fixed jsUri escaping problems

bower.json, strata.js
@jtrantin @gandhikeyur Please review
=> PCM-3222 Filtering out helper solutions

bower.json, strata.js
@engineersamuel @renujhamtani Please review.
=> PCM-3325: Adding quotes to case_owner SOLR criteria

bower.json, strata.js
=> PCM-3048: Added format to cases.advancedSearch

bower.json, strata.js
=> PCM-3162: Added progress callback for uploading attachments 

bower.json, strata.js
@vrathee @gandhikeyur I realized we need to handle the scenario when the progress callback is not passed, not doing that could lead to problems for existing code. Please review.
=> PCM-3162: Handling progress callback if not passed

bower.json, strata.js
@renujhamtani @jtrantin Please review
https://projects.engineering.redhat.com/browse/PCM-3174
=> Pcm 3174 -  Api for adding public/pvt attachment

bower.json, strata.js
@jtrantin @renujhamtani Please review
https://projects.engineering.redhat.com/browse/PCM-4334
=> API changes for PCM-4334

bower.json, strata.js
@vrathee @renujhamtani Please review.
https://projects.engineering.redhat.com/browse/PCM-4460 
https://projects.engineering.redhat.com/browse/PCM-4260
=> pcm-4460 : secure support portal changes

bower.json, strata.js
@vrathee @kunyan @engineersamuel Please review.
=> pcm-4460 code changes

bower.json, strata.js
@vrathee @engineersamuel Please review.
https://projects.engineering.redhat.com/browse/PCM-4137
=> pcm-4137 code changes

bower.json, strata.js
@engineersamuel @anujsi @kunyan @vrathee @renujhamtani Please review.
https://projects.engineering.redhat.com/browse/PCM-5350
=> pcm-5350 : solution engine code changes

bower.json, strata.js
@engineersamuel @renujhamtani @anujsi Please review
https://projects.engineering.redhat.com/browse/PCM-5386
=> pcm-5386 fetching recommendations of all types

bower.json, strata.js
@gandhikeyur @engineersamuel Please review.
https://projects.engineering.redhat.com/browse/PCM-5905
=> pcm-5905 : case list does not show next page .

bower.json, strata.js
@anujsi @engineersamuel Please review
https://projects.engineering.redhat.com/browse/PCM-6249
=> pcm-6249 adding valid documentKinds to rs/recommendations call

strata.js
@vrathee @gandhikeyur I could not add reviewers so I just mentioned you two.
=> PCM-7419: Added logic to return a specific error for when an xhr is aborted

bower.json, strata.js
=> adds token refresh to strata calls

strata.js
@anujsi please review
blocked by:
https://github.com/redhataccess/stratajs/pull/66
=> PCM-8117: adding queries to advanced search

strata.js
=> fixed jwt refresh and ajax call function

strata.js
@anujsi please review
blocked by:
https://github.com/redhataccess/stratajs/pull/66
=> PCM-8058: changed query to use new strata search

.gitignore, bower.json, strata.js
@jeudy100 @vrathee Please review.
https://projects.engineering.redhat.com/browse/PCM-8469
=> PCM-8469 - Advanced case search not returning expected results .
